<?php

namespace Modules\Mosque\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MosqueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mosques')->insert([
            [
                'name' => 'مسجد الرحمن',
                'image' => 'mosques/mosque1.png',
                'working_hours' => '5:00 AM - 10:00 PM',
                'status' => 'active',
                'is_featured' => true,
                'city' => 'دمشق',
                'district' => 'المزة',
                'latitude' => 33.5138,
                'longitude' => 36.2765,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ أحمد',
                'khatib' => 'الشيخ عبد الله',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'مسجد النور',
                'image' => 'mosques/mosque2.png',
                'working_hours' => '4:30 AM - 11:00 PM',
                'status' => 'active',
                'is_featured' => false,
                'city' => 'حلب',
                'district' => 'السليمانية',
                'latitude' => 36.2021,
                'longitude' => 37.1343,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ محمد',
                'khatib' => 'الشيخ يوسف',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'مسجد الإيمان',
                'image' => 'mosques/mosque3.png',
                'working_hours' => '5:00 AM - 9:30 PM',
                'status' => 'active',
                'is_featured' => true,
                'city' => 'حمص',
                'district' => 'باب السباع',
                'latitude' => 34.7324,
                'longitude' => 36.7182,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ عمر',
                'khatib' => 'الشيخ خالد',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'مسجد التقوى',
                'image' => 'mosques/mosque2.png',
                'working_hours' => '5:15 AM - 10:15 PM',
                'status' => 'active',
                'is_featured' => false,
                'city' => 'اللاذقية',
                'district' => 'الصليبة',
                'latitude' => 35.5317,
                'longitude' => 35.7901,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ حسن',
                'khatib' => 'الشيخ محمود',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'مسجد الرحمن',
                'image' => 'mosques/mosque1.png',
                'working_hours' => '5:00 AM - 10:00 PM',
                'status' => 'active',
                'is_featured' => true,
                'city' => 'دمشق',
                'district' => 'المزة',
                'latitude' => 33.5138,
                'longitude' => 36.2765,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ أحمد',
                'khatib' => 'الشيخ عبد الله',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'مسجد النور',
                'image' => 'mosques/mosque2.png',
                'working_hours' => '4:30 AM - 11:00 PM',
                'status' => 'active',
                'is_featured' => false,
                'city' => 'حلب',
                'district' => 'السليمانية',
                'latitude' => 36.2021,
                'longitude' => 37.1343,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ محمد',
                'khatib' => 'الشيخ يوسف',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'مسجد الإيمان',
                'image' => 'mosques/mosque3.png',
                'working_hours' => '5:00 AM - 9:30 PM',
                'status' => 'active',
                'is_featured' => true,
                'city' => 'حمص',
                'district' => 'باب السباع',
                'latitude' => 34.7324,
                'longitude' => 36.7182,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ عمر',
                'khatib' => 'الشيخ خالد',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'مسجد التقوى',
                'image' => 'mosques/mosque2.png',
                'working_hours' => '5:15 AM - 10:15 PM',
                'status' => 'active',
                'is_featured' => false,
                'city' => 'اللاذقية',
                'district' => 'الصليبة',
                'latitude' => 35.5317,
                'longitude' => 35.7901,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ حسن',
                'khatib' => 'الشيخ محمود',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'مسجد الرحمن',
                'image' => 'mosques/mosque1.png',
                'working_hours' => '5:00 AM - 10:00 PM',
                'status' => 'active',
                'is_featured' => true,
                'city' => 'دمشق',
                'district' => 'المزة',
                'latitude' => 33.5138,
                'longitude' => 36.2765,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ أحمد',
                'khatib' => 'الشيخ عبد الله',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'مسجد النور',
                'image' => 'mosques/mosque2.png',
                'working_hours' => '4:30 AM - 11:00 PM',
                'status' => 'active',
                'is_featured' => false,
                'city' => 'حلب',
                'district' => 'السليمانية',
                'latitude' => 36.2021,
                'longitude' => 37.1343,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ محمد',
                'khatib' => 'الشيخ يوسف',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'مسجد الإيمان',
                'image' => 'mosques/mosque3.png',
                'working_hours' => '5:00 AM - 9:30 PM',
                'status' => 'active',
                'is_featured' => true,
                'city' => 'حمص',
                'district' => 'باب السباع',
                'latitude' => 34.7324,
                'longitude' => 36.7182,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ عمر',
                'khatib' => 'الشيخ خالد',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'مسجد التقوى',
                'image' => 'mosques/mosque2.png',
                'working_hours' => '5:15 AM - 10:15 PM',
                'status' => 'active',
                'is_featured' => false,
                'city' => 'اللاذقية',
                'district' => 'الصليبة',
                'latitude' => 35.5317,
                'longitude' => 35.7901,
                'average_rating' => 0,
                'reviews_count' => 0,
                'imam' => 'الشيخ حسن',
                'khatib' => 'الشيخ محمود',
                'manager_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ]);
        
    }
}
