<?php

namespace Modules\Donation\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DonationSeeder extends Seeder
{
    public function run(): void
    {
        $donations = [
            [
                'reference' => 'DON-00001',
                'mosque_id' => 1,
                'user_id' => 5,
                'campaign_id' => 1,
                'mosque_need_id' => null,
                'donation_type' => 'cash',
                'payment_method' => 'cash',
                'amount' => 5000,
                'currency' => 'SYP',
                'exchange_rate' => 1,
                'base_amount' => 5000,
                'item_description' => null,
                'donor_name' => 'أحمد محمد',
                'status' => 'completed',
                'completed_at' => '2025-01-15 10:30:00',
            ],
            [
                'reference' => 'DON-00002',
                'mosque_id' => 1,
                'user_id' => null,
                'campaign_id' => 1,
                'mosque_need_id' => null,
                'donation_type' => 'cash',
                'payment_method' => 'cash',
                'amount' => 10000,
                'currency' => 'SYP',
                'exchange_rate' => 1,
                'base_amount' => 10000,
                'item_description' => null,
                'donor_name' => 'فاعل خير',
                'status' => 'completed',
                'completed_at' => '2025-02-01 14:00:00',
            ],
            [
                'reference' => 'DON-00003',
                'mosque_id' => 1,
                'user_id' => 5,
                'campaign_id' => 2,
                'mosque_need_id' => null,
                'donation_type' => 'cash',
                'payment_method' => 'stripe',
                'amount' => 25000,
                'currency' => 'SYP',
                'exchange_rate' => 1,
                'base_amount' => 25000,
                'item_description' => null,
                'donor_name' => 'خالد عمر',
                'status' => 'completed',
                'completed_at' => '2024-07-15 09:00:00',
            ],
            [
                'reference' => 'DON-00004',
                'mosque_id' => 2,
                'user_id' => 5,
                'campaign_id' => 3,
                'mosque_need_id' => null,
                'donation_type' => 'cash',
                'payment_method' => 'cash',
                'amount' => 10000,
                'currency' => 'SYP',
                'exchange_rate' => 1,
                'base_amount' => 10000,
                'item_description' => null,
                'donor_name' => 'سارة أحمد',
                'status' => 'completed',
                'completed_at' => '2025-03-15 11:00:00',
            ],
            [
                'reference' => 'DON-00005',
                'mosque_id' => 2,
                'user_id' => null,
                'campaign_id' => 3,
                'mosque_need_id' => null,
                'donation_type' => 'cash',
                'payment_method' => 'cash',
                'amount' => 5000,
                'currency' => 'SYP',
                'exchange_rate' => 1,
                'base_amount' => 5000,
                'item_description' => null,
                'donor_name' => 'فاعل خير',
                'status' => 'pending',
                'completed_at' => null,
            ],
            [
                'reference' => 'DON-00006',
                'mosque_id' => 3,
                'user_id' => 1,
                'campaign_id' => null,
                'mosque_need_id' => null,
                'donation_type' => 'cash',
                'payment_method' => 'stripe',
                'amount' => 50000,
                'currency' => 'SYP',
                'exchange_rate' => 1,
                'base_amount' => 50000,
                'item_description' => null,
                'donor_name' => 'محمد علي',
                'status' => 'completed',
                'completed_at' => '2025-04-01 16:30:00',
            ],
            [
                'reference' => 'DON-00007',
                'mosque_id' => 4,
                'user_id' => null,
                'campaign_id' => null,
                'mosque_need_id' => null,
                'donation_type' => 'cash',
                'payment_method' => 'cash',
                'amount' => 1000,
                'currency' => 'SYP',
                'exchange_rate' => 1,
                'base_amount' => 1000,
                'item_description' => null,
                'donor_name' => 'فاعل خير',
                'status' => 'pending',
                'completed_at' => null,
            ],
            [
                'reference' => 'DON-00008',
                'mosque_id' => 1,
                'user_id' => null,
                'campaign_id' => null,
                'mosque_need_id' => null,
                'donation_type' => 'in_kind',
                'payment_method' => 'cash',
                'amount' => null,
                'currency' => 'SYP',
                'exchange_rate' => 1,
                'base_amount' => 0,
                'item_description' => 'مواد غذائية متنوعة',
                'donor_name' => 'مؤسسة الخير',
                'status' => 'completed',
                'completed_at' => '2025-01-20 12:00:00',
            ],
        ];

        DB::table('donations')->insert($donations);
    }
}
